apiVersion: v1
kind: Namespace
metadata:
  name: limited-namespace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limit-range
  namespace: limited-namespace
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 500m
      memory: 512Mi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container
  - max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: limited-namespace
spec:
  containers:
  - name: app
    image: nginx:1.21
    # No resources specified - will get defaults from LimitRange