apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:13
            command:
            - /bin/bash
            - -c
            - |
              echo "Starting backup at $(date)"
              pg_dump -h postgres-service -U postgres mydb > /backup/backup-$(date +%Y%m%d).sql
              echo "Backup completed at $(date)"
            env:
            - name: PGPASSWORD
              value: password # WARNING: Hardcoding passwords is not recommended in production. Consider using a Secret.
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure