apiVersion: v1
kind: Pod
metadata:
  name: debug-toolkit
spec:
  containers:
  - name: debug
    image: nicolaka/netshoot:latest
    command: ['sleep', '3600']
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_PTRACE"] # WARNING: This gives the container elevated privileges.
    volumeMounts:
    - name: proc
      mountPath: /host/proc
      readOnly: true
    - name: sys
      mountPath: /host/sys
      readOnly: true
  volumes:
  - name: proc
    hostPath:
      path: /proc
  - name: sys
    hostPath:
      path: /sys
  hostNetwork: true # WARNING: This gives the container access to the host's network stack.
  hostPID: true # WARNING: This gives the container access to the host's process ID namespace.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-scripts
data:
  debug-pod.sh: |
    #!/bin/bash
    POD_NAME=$1
    NAMESPACE=${2:-default}
    
    echo "=== Pod Information ==="
    kubectl get pod $POD_NAME -n $NAMESPACE -o wide
    
    echo "=== Pod Description ==="
    kubectl describe pod $POD_NAME -n $NAMESPACE
    
    echo "=== Pod Logs ==="
    kubectl logs $POD_NAME -n $NAMESPACE --tail=50
    
    echo "=== Pod Events ==="
    kubectl get events -n $NAMESPACE --field-selector involvedObject.name=$POD_NAME
    
    echo "=== Resource Usage ==="
    kubectl top pod $POD_NAME -n $NAMESPACE
  
  debug-network.sh: |
    #!/bin/bash
    SERVICE_NAME=$1
    NAMESPACE=${2:-default}
    
    echo "=== Service Information ==="
    kubectl get svc $SERVICE_NAME -n $NAMESPACE -o wide
    
    echo "=== Endpoints ==="
    kubectl get endpoints $SERVICE_NAME -n $NAMESPACE
    
    echo "=== DNS Resolution ==="
    kubectl run dns-test --image=busybox:1.35 --rm -it --restart=Never -- nslookup $SERVICE_NAME.$NAMESPACE.svc.cluster.local
    
    echo "=== Connectivity Test ==="
    kubectl run connectivity-test --image=busybox:1.35 --rm -it --restart=Never -- wget -qO- $SERVICE_NAME.$NAMESPACE.svc.cluster.local
  
  debug-storage.sh: |
    #!/bin/bash
    PVC_NAME=$1
    NAMESPACE=${2:-default}
    
    echo "=== PVC Information ==="
    kubectl get pvc $PVC_NAME -n $NAMESPACE -o wide
    
    echo "=== PV Information ==="
    PV_NAME=$(kubectl get pvc $PVC_NAME -n $NAMESPACE -o jsonpath='{.spec.volumeName}')
    kubectl get pv $PV_NAME -o wide
    
    echo "=== Storage Class ==="
    SC_NAME=$(kubectl get pvc $PVC_NAME -n $NAMESPACE -o jsonpath='{.spec.storageClassName}')
    kubectl get storageclass $SC_NAME
    
    echo "=== Events ==="
    kubectl get events -n $NAMESPACE --field-selector involvedObject.name=$PVC_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-app
  template:
    metadata:
      labels:
        app: debug-app
    spec:
      containers:
      - name: app
        image: busybox:1.35
        command: ['sh', '-c', 'while true; do echo "Debug app running..."; sleep 30; done']
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: LOG_LEVEL
          value: "debug"