apiVersion: v1
kind: Namespace
metadata:
  name: cost-optimized
  labels:
    cost-center: "engineering"
    environment: "production"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cost-quota
  namespace: cost-optimized
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "5"
    requests.storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-optimized-app
  namespace: cost-optimized
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cost-optimized-app
  template:
    metadata:
      labels:
        app: cost-optimized-app
    spec:
      nodeSelector:
        node-type: spot
      containers:
      - name: app
        image: nginx:1.21-alpine
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi