apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-reader
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: api-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: api-reader
  namespace: default
roleRef:
  kind: Role
  name: api-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: api-client
spec:
  serviceAccountName: api-reader
  containers:
  - name: client
    image: bitnami/kubectl:latest
    command: ['sleep', '3600']
---
apiVersion: v1
kind: Pod
metadata:
  name: no-token-pod
spec:
  serviceAccountName: api-reader
  automountServiceAccountToken: false
  containers:
  - name: app
    image: nginx:1.21