apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password
  host: bG9jYWxob3N0    # localhost
---
apiVersion: v1
kind: Pod
metadata:
  name: database-client
spec:
  containers:
  - name: client
    image: postgres:13
    command: ['sleep', '3600']
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: password
    - name: POSTGRES_HOST
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: host