apiVersion: v1
kind: Pod
metadata:
  name: crashloop-example
spec:
  containers:
  - name: failing-app
    image: busybox:1.35
    command: ['sh', '-c', 'echo "Starting app..." && sleep 5 && echo "App crashed!" && exit 1']
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: imagepull-example
spec:
  containers:
  - name: nonexistent-image
    image: nonexistent/image:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: resource-limit-example
spec:
  containers:
  - name: memory-hog
    image: busybox:1.35
    command: ['sh', '-c', 'dd if=/dev/zero of=/tmp/memory.dat bs=1M count=1000']
    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-test-pod
spec:
  containers:
  - name: dns-test
    image: busybox:1.35
    command: ['sleep', '3600']
---
apiVersion: v1
kind: Service
metadata:
  name: broken-service
spec:
  selector:
    app: nonexistent-app
  ports:
  - port: 80
    targetPort: 8080