apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - name: app-container
    image: busybox:1.35
    command: ['sh', '-c', 'echo "Environment: $ENV_NAME, Version: $APP_VERSION" && sleep 3600']
    env:
    - name: ENV_NAME
      value: "development"
    - name: APP_VERSION
      value: "1.0.0"
    - name: DEBUG_MODE
      value: "true"