apiVersion: v1
kind: Pod
metadata:
  name: command-pod
spec:
  containers:
  - name: custom-app
    image: busybox:1.35
    command: ['sh']
    args: ['-c', 'while true; do echo "Hello from Kubernetes Pod at $(date)"; sleep 10; done']
  restartPolicy: Never