apiVersion: v1
kind: Pod
metadata:
  name: labeled-pod
  labels:
    app: nginx
    environment: development
    version: v1.0
  annotations:
    description: "This is a sample pod with labels and annotations"
    created-by: "kubernetes-guide"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80