apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  containers:
  - name: writer
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do echo "$(date): Hello from writer" >> /shared/data.txt; sleep 10; done']
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
  - name: reader
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do echo "Reading:"; cat /shared/data.txt; sleep 15; done']
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
  volumes:
  - name: shared-storage
    emptyDir: {}