apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-configs
  namespace: multi-cluster
data:
  cluster-east.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: cluster-east
      cluster:
        server: https://cluster-east.example.com
        certificate-authority-data: LS0tLS1CRUdJTi...
    users:
    - name: cluster-east-user
      user:
        token: eyJhbGciOiJSUzI1NiIs...
    contexts:
    - name: cluster-east-context
      context:
        cluster: cluster-east
        user: cluster-east-user
    current-context: cluster-east-context
  
  cluster-west.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: cluster-west
      cluster:
        server: https://cluster-west.example.com
        certificate-authority-data: LS0tLS1CRUdJTi...
    users:
    - name: cluster-west-user
      user:
        token: eyJhbGciOiJSUzI1NiIs...
    contexts:
    - name: cluster-west-context
      context:
        cluster: cluster-west
        user: cluster-west-user
    current-context: cluster-west-context
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cluster-controller
  namespace: multi-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-cluster-controller
  template:
    metadata:
      labels:
        app: multi-cluster-controller
    spec:
      containers:
      - name: controller
        image: bitnami/kubectl:latest
        command: ['sleep', '3600']
        volumeMounts:
        - name: cluster-configs
          mountPath: /etc/clusters
        env:
        - name: KUBECONFIG
          value: "/etc/clusters/cluster-east.yaml:/etc/clusters/cluster-west.yaml"
      volumes:
      - name: cluster-configs
        configMap:
          name: cluster-configs
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cross-cluster-sync
  namespace: multi-cluster
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting cross-cluster sync..."
              
              # Check cluster health
              kubectl --kubeconfig=/etc/clusters/cluster-east.yaml cluster-info
              kubectl --kubeconfig=/etc/clusters/cluster-west.yaml cluster-info
              
              # Sync ConfigMaps across clusters
              kubectl --kubeconfig=/etc/clusters/cluster-east.yaml get configmap global-config -o yaml | \
                kubectl --kubeconfig=/etc/clusters/cluster-west.yaml apply -f -
              
              echo "Cross-cluster sync completed"
            volumeMounts:
            - name: cluster-configs
              mountPath: /etc/clusters
          volumes:
          - name: cluster-configs
            configMap:
              name: cluster-configs
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: global-service
  namespace: multi-cluster
  annotations:
    service.kubernetes.io/load-balancer-class: "global"
spec:
  type: LoadBalancer
  selector:
    app: global-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-app
  namespace: multi-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: global-app
  template:
    metadata:
      labels:
        app: global-app
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 8080
        env:
        - name: CLUSTER_REGION
          value: "us-east-1"